# Generated by Django 4.0.1 on 2022-01-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userfollower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollower',
            old_name='user',
            new_name='following',
        ),
    ]
