# Generated by Django 4.0.1 on 2022-02-01 14:33

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userfollower_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='users/default.jpg', null=True, upload_to='users/'),
        ),
    ]
