# Generated by Django 4.0.1 on 2022-02-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollower',
        ),
    ]
